name: Deploy Backend

on:
  # Tá»± Ä‘á»™ng cháº¡y khi push vÃ o nhÃ¡nh main vÃ  cÃ³ sá»­a Ä‘á»•i trong thÆ° má»¥c backend
  push:
    branches: ["main"]
    paths: ["backend/**"]
  # Cho phÃ©p báº¥m nÃºt cháº¡y thá»§ cÃ´ng
  workflow_dispatch:

jobs:
  deploy-be:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Láº¥y code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Upload PHP vÃ o htdocs/api
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend/
          server-dir: /htdocs/api/
          protocol: ftp
          port: 21
