name: Deploy Backend

on:
  push:
    branches: ["main"]
    paths: ["backend/**"] # Chá»‰ cháº¡y khi sá»­a Backend

jobs:
  deploy-be:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Láº¥y code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Upload PHP vÃ o htdocs/api
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./backend/
          server-dir: /htdocs/api/
          # --- THÃŠM 2 DÃ’NG NÃ€Y ---
          protocol: ftp
          port: 21
