name: Deploy Frontend

on:
  # T·ª± ƒë·ªông ch·∫°y khi push v√†o nh√°nh main v√† c√≥ s·ª≠a ƒë·ªïi trong th∆∞ m·ª•c frontend
  push:
    branches: ["main"]
    paths: ["frontend/**"]
  # Cho ph√©p b·∫•m n√∫t ch·∫°y th·ªß c√¥ng (Tab Actions)
  workflow_dispatch:

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    steps:
      - name: üöö L·∫•y code
        uses: actions/checkout@v4

      - name: üìÇ Upload HTML v√†o htdocs
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/
          server-dir: /htdocs/
          # B·∫£o v·ªá th∆∞ m·ª•c api v√† git
          exclude: |
            api/**
            **/.git*
          # C·∫•u h√¨nh gi·∫£m l·ªói k·∫øt n·ªëi InfinityFree
          protocol: ftp
          port: 21
