name: Deploy Frontend

on:
  push:
    branches: ["main"]
    paths: ["frontend/**"] # Ch·ªâ ch·∫°y khi s·ª≠a Frontend

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    steps:
      - name: üöö L·∫•y code
        uses: actions/checkout@v4

      - name: üìÇ Upload HTML v√†o htdocs
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/
          server-dir: /htdocs/
          # Quan tr·ªçng: exclude ƒë·ªÉ kh√¥ng l·ª° tay x√≥a m·∫•t th∆∞ m·ª•c api c·ªßa backend
          exclude: |
            api/**
            **/.git*
