name: Deploy Frontend

on:
  push:
    branches: ["main"]
    paths: ["frontend/**"] # Chá»‰ cháº¡y khi sá»­a Frontend

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Láº¥y code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Upload HTML vÃ o htdocs
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/
          server-dir: /htdocs/
          exclude: |
            api/**
            **/.git*
          # --- THÃŠM 2 DÃ’NG NÃ€Y ---
          protocol: ftp
          port: 21
